name: .NET Core Tests and Deployments

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  unit_test_develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Api/Api.csproj

      # Run unit tests
      - name: Run unit tests
        run: dotnet test tests/Domain.Tests/Domain.Tests.csproj

  code_analysis:
    runs-on: ubuntu-latest
    needs: unit_test_develop

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Api/Api.csproj

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_GIT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner begin /k:sofarc6soat /d:sonar.login=${{ secrets.SONAR_TOKEN }} && \
            dotnet build src/Api/Api.csproj --configuration Release && \
            dotnet sonarscanner end            

  deploy_develop:
    if: github.ref == 'refs/heads/develop'
    needs: code_analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build application
      - name: Build application
        run: dotnet build src/Api/Api.csproj --configuration Release

      # Deploy application (add your deploy steps here)
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deploy commands here

  smoketest_develop:
    if: github.ref == 'refs/heads/develop'
    needs: deploy_develop
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install necessary tools for smoke testing
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      # Run smoke tests
      - name: Run smoke tests
        run: dotnet test tests/SmokeTests/SmokeTests.csproj

  unit_test_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Api/Api.csproj

      # Run unit tests
      - name: Run unit tests
        run: dotnet test tests/Domain.Tests/Domain.Tests.csproj

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: unit_test_main
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build application
      - name: Build application
        run: dotnet build src/Api/Api.csproj --configuration Release

      # Deploy application (add your deploy steps here)
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deploy commands here

  smoketest_main:
    if: github.ref == 'refs/heads/main'
    needs: deploy_main
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Install necessary tools for smoke testing
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      # Run smoke tests
      - name: Run smoke tests
        run: dotnet test tests/SmokeTests/SmokeTests.csproj

  publish_docker_image:
    if: github.ref == 'refs/heads/main'
    needs: smoketest_main
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2
        with:
          use-buildkit: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sofarc6soat/quickfood-backend:latest -f ../src/Api/Dockerfile .
       
      - name: Push Docker Image
        run: docker push sofarc6soat/quickfood-backend:latest

 
