name: .NET Core Tests and Smoke Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/Api/Api.csproj

      # Run unit tests
      - name: Run unit tests
        run: dotnet test tests/Domain.Tests/Domain.Tests.csproj

  deploy_and_smoke_test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Build application
      - name: Build application
        run: dotnet build src/Api/Api.csproj --configuration Release

      # Run smoke tests
      - name: Run smoke tests
        run: |
          # Install necessary tools for smoke testing
          sudo apt-get update
          sudo apt-get install -y curl

          # Run smoke tests
          dotnet test tests/SmokeTests/SmokeTests.csproj
